# Generated by Django 3.1.4 on 2020-12-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201225_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commemt',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.category', verbose_name='category'),
        ),
    ]
