version: '3.8'
services:
  db:
    image: sqlite3
  web:
    build: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/forum
    ports:
      - "8000:8000"
    depends_on:
      - db